var annotated =
[
    [ "AsymmetricQuantizationError", "structAsymmetricQuantizationError.html", "structAsymmetricQuantizationError" ],
    [ "CombinedError", "structCombinedError.html", "structCombinedError" ],
    [ "DepthColorArraySizeMismatch", "structDepthColorArraySizeMismatch.html", "structDepthColorArraySizeMismatch" ],
    [ "DepthModel", "classDepthModel.html", "classDepthModel" ],
    [ "InvalidFloat32QuantizationTypeError", "structInvalidFloat32QuantizationTypeError.html", "structInvalidFloat32QuantizationTypeError" ],
    [ "InvalidInputFormatForModel", "structInvalidInputFormatForModel.html", "structInvalidInputFormatForModel" ],
    [ "InvalidInputFormatForOperator", "structInvalidInputFormatForOperator.html", "structInvalidInputFormatForOperator" ],
    [ "InvalidQuantizedType", "structInvalidQuantizedType.html", "structInvalidQuantizedType" ],
    [ "MiDaSImageOperator", "classMiDaSImageOperator.html", "classMiDaSImageOperator" ],
    [ "MutexGuard", "classMutexGuard.html", "classMutexGuard" ],
    [ "Operator", "classOperator.html", "classOperator" ],
    [ "OperatorBase", "classOperatorBase.html", "classOperatorBase" ],
    [ "OperatorChain", "classOperatorChain.html", "classOperatorChain" ],
    [ "OperatorError", "structOperatorError.html", "structOperatorError" ],
    [ "Overloads", "structOverloads.html", null ],
    [ "ProfileScope", "structProfileScope.html", "structProfileScope" ],
    [ "ProfileScopeRecord", "structProfileScopeRecord.html", "structProfileScopeRecord" ],
    [ "ProfilingFrame", "classProfilingFrame.html", "classProfilingFrame" ],
    [ "QuantizationElementsMismatch", "structQuantizationElementsMismatch.html", "structQuantizationElementsMismatch" ],
    [ "RelativeDepthPostOperator", "classRelativeDepthPostOperator.html", "classRelativeDepthPostOperator" ],
    [ "TensorType", "classTensorType.html", "classTensorType" ],
    [ "TfLiteAllocateTensorsError", "structTfLiteAllocateTensorsError.html", "structTfLiteAllocateTensorsError" ],
    [ "TfLiteCopyFromInputTensorError", "structTfLiteCopyFromInputTensorError.html", "structTfLiteCopyFromInputTensorError" ],
    [ "TfLiteCopyToOutputTensorError", "structTfLiteCopyToOutputTensorError.html", "structTfLiteCopyToOutputTensorError" ],
    [ "TfLiteCreateInterpreterError", "structTfLiteCreateInterpreterError.html", "structTfLiteCreateInterpreterError" ],
    [ "TfLiteInvokeInterpreterError", "structTfLiteInvokeInterpreterError.html", "structTfLiteInvokeInterpreterError" ],
    [ "TfLiteNonFloatTensorTypeError", "structTfLiteNonFloatTensorTypeError.html", "structTfLiteNonFloatTensorTypeError" ],
    [ "TfLiteReporterUserData", "structTfLiteReporterUserData.html", "structTfLiteReporterUserData" ],
    [ "TfLiteRuntime", "classTfLiteRuntime.html", "classTfLiteRuntime" ],
    [ "TfLiteTensorElementCountMismatch", "structTfLiteTensorElementCountMismatch.html", "structTfLiteTensorElementCountMismatch" ],
    [ "TfLiteTensorsNotCreatedError", "structTfLiteTensorsNotCreatedError.html", "structTfLiteTensorsNotCreatedError" ],
    [ "UnexpectedOperatorOutputFormat", "structUnexpectedOperatorOutputFormat.html", "structUnexpectedOperatorOutputFormat" ],
    [ "YoloImageOperator", "classYoloImageOperator.html", "classYoloImageOperator" ],
    [ "YoloModel", "classYoloModel.html", "classYoloModel" ]
];